name: github_star_gazer

packages:
  - packages/**

scripts:
  install:
    run: flutter pub get
    exec:
      concurrency: 1
      failFast: true
    description: Install dependencies
    packageFilters:
      flutter: true

  generate:dart:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      failFast: true
    description: Code generation
    packageFilters:
      dependsOn: "build_runner"
      flutter: true
