name: github_star_gazer
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  webview_flutter: ^4.7.0
  auth:
    path: packages/auth
  core:
    path: packages/core
  github:
    path: packages/github
  search:
    path: packages/search
  url_launcher: ^6.2.4
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  material_floating_search_bar_2: ^0.5.0
  flutter_riverpod: ^2.4.10

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  melos: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon-1024x1024.png"
