name: auth
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  oauth2: ^2.0.2
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - .env
